In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

In [2]:
rng = np.random.default_rng(seed = 42)

1 How likely is it that you roll doubles when rolling two dice?

In [21]:
roll = rng.choice([1,2,3,4,5,6],(1_000,2))
roll[:5]

array([[1, 1],
       [4, 2],
       [3, 1],
       [2, 3],
       [5, 3]])

In [22]:
double_roll = (roll[:,0] == roll[:,1]).sum()

In [23]:
double_roll / len(roll)

0.184

2 If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?



In [47]:
flips = rng.choice([0,1],(1_000,8))
flips[:25]

array([[1, 0, 0, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 1, 1, 0, 0],
       [0, 1, 1, 1, 1, 0, 1, 0],
       [1, 0, 1, 1, 1, 1, 0, 0],
       [0, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 0, 0, 1, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 0, 1],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [1, 0, 1, 1, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 0, 0, 0],
       [1, 0, 1, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 0],
       [1, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 0, 1, 0, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 0, 1, 1],
       [1, 0, 0, 0, 1, 0, 1, 0]])

In [58]:
triple_h = (flips == 1).sum(axis=1) == 3
triple_h[:5]

array([False, False,  True, False, False])

In [56]:
total_triple = triple_h.sum()

In [57]:
total_triple / len(flips)

0.219

3 There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [59]:
cohorts = rng.choice([0,0,0,1],(1_000,2))

In [60]:
cohorts

array([[1, 0],
       [0, 0],
       [0, 0],
       ...,
       [0, 0],
       [1, 0],
       [0, 0]])

In [63]:
double_data = (cohorts.sum(axis= 1) == 2).sum()

In [64]:
double_data / len(cohorts)

0.056

5 Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [73]:
manh = np.random.normal(178, 8, (1_000,1))
womanh = np.random.normal(170, 6, (1_000,1))

In [205]:
manh

array([[187.32943261],
       [185.14757976],
       [183.83031531],
       [181.40427764],
       [178.37445514],
       [186.29822011],
       [183.14856482],
       [170.43687964],
       [182.12158249],
       [183.06362967],
       [181.1949844 ],
       [160.62000434],
       [166.69264616],
       [180.85056562],
       [156.74159083],
       [165.67658666],
       [175.41258535],
       [181.98398078],
       [168.58183123],
       [173.40242827],
       [169.39938519],
       [175.69082355],
       [179.53753383],
       [168.78196452],
       [190.87585807],
       [174.66819963],
       [181.12172289],
       [190.00977794],
       [163.83529342],
       [183.27284238],
       [174.6797245 ],
       [173.4745459 ],
       [180.41527133],
       [189.72713691],
       [164.68987686],
       [178.31678323],
       [175.68850999],
       [177.40590551],
       [180.73910208],
       [175.86929408],
       [170.84011951],
       [174.717704  ],
       [188.98564229],
       [178

In [102]:
womanh.shape

(1000, 1)

In [106]:
taller_w = (manh < womanh).sum()
taller_w

215

In [95]:
taller_w / len(manh)

0.215

In [101]:
heights = np.column_stack((manh, womanh))
heights

array([[187.32943261, 177.10480078],
       [185.14757976, 164.28093406],
       [183.83031531, 169.34510078],
       ...,
       [171.85166546, 172.96782342],
       [173.54730069, 173.15156494],
       [193.9795115 , 170.77303398]])

In [105]:
(heights[:,0] < heights[:,1]).sum()

215

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [148]:
corrupt = 1/250
corrupt

0.004

In [121]:
installs_fifty = rng.random((1_000,50))
installs_fifty[:1]

array([[0.46822656, 0.95701862, 0.77709831, 0.55302764, 0.32704866,
        0.02376303, 0.67771646, 0.15544531, 0.15706505, 0.10452031,
        0.88101031, 0.5777048 , 0.80294845, 0.01504062, 0.47547648,
        0.62451864, 0.9160483 , 0.59910233, 0.13147889, 0.71049408,
        0.35644896, 0.24245127, 0.84894524, 0.55932935, 0.4926103 ,
        0.84102356, 0.94092129, 0.63883538, 0.84500319, 0.42223891,
        0.90349557, 0.7193483 , 0.91067182, 0.86392629, 0.3554776 ,
        0.88450044, 0.54511202, 0.79515904, 0.70946605, 0.92426986,
        0.7040617 , 0.72057855, 0.99691867, 0.86896851, 0.61241647,
        0.75063534, 0.25526104, 0.54853599, 0.98163741, 0.17176752]])

In [160]:
corrumption_fifty = (installs_fifty <= corrupt).sum(axis= 1)
fifty_total = corrumption_fifty.sum()

50 Installs

In [166]:
1 - (fifty_total / len(installs_fifty))

0.798

100 installs

In [ ]:
installs_hund = rng.random((1_000,100))

In [170]:
corrumption_hund = (installs_hund <= corrupt).sum(axis= 1)
hun_total = corrumption_hund.sum()
1 - (hun_total / len(installs_hund))

0.605

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [172]:
installs_hundfifty = rng.random((1_000,1))

In [174]:
corrumption_hundfifty = (installs_hundfifty <= corrupt).sum()
hunfifty_total = corrumption_hundfifty.sum()
(hunfifty_total / len(installs_hundfifty))

0.002

How likely is it that 450 students all download anaconda without an issue?

In [175]:
installs_fourfifty = rng.random((1_000,450)) 

In [183]:
corruption_fourfifty = (installs_fourfifty <= corrupt).sum(axis= 1)
total_fourfifty = (corruption_fourfifty > 0).sum()
1 - (total_fourfifty / len(installs_fourfifty))

0.14800000000000002

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

In [192]:
truckday = rng.random((1000, 3))
truckday[:5]

array([[1.10803300e-04, 6.16960561e-02, 1.60830350e-01],
       [8.44483045e-01, 5.60619021e-01, 4.47897601e-01],
       [3.57598313e-01, 6.15119884e-01, 3.57645127e-01],
       [3.79268770e-02, 3.80339009e-01, 2.95960317e-01],
       [8.30117879e-01, 7.27269328e-01, 7.68047465e-01]])

In [200]:
no_truck = ((truckday >= .7).sum(axis= 1) ==0).sum()
no_truck

347

In [201]:
no_truck / len(truckday)

0.347

In [244]:
two_three = rng.choice(range(1,366),(1_000,23))
df_two_three = pd.DataFrame(two_three)
df_two_three.head()

0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0   95  275  158  309  351  235  104  161    2  264  ...  244  233  156  183   
1   38  251  343   50  203  129  117  318  236  186  ...  315   48   59  321   
2  164  188  138  340  278  174   35  313   64  187  ...  308  102  132   89   
3  212  226  208  245  167  215   62  279   44  111  ...  351  147  199  323   
4  270  284  220  304  100  324  231  274   14   70  ...  357  342  191   92   

    17   18   19   20   21   22  
0   62  338  252    9  133  240  
1  280  271  171  200  146  185  
2  136  341  246  336   23  231  
3   40   97  110  223  164  317  
4  232  135  208  351   88  336  

[5 rows x 23 columns]

23 Students

In [245]:
unique_df = df_two_three.nunique(axis=1)
total_nonunique = (unique_df < 23).sum()
total_nonunique / len(unique_df)

0.47

20 Students

In [246]:
twenty = rng.choice(range(1,366),(1_000,23))
df_twenty = pd.DataFrame(twenty)
unique_df_twenty = df_twenty.nunique(axis=1)
total_nonunique_twenty = (unique_df_twenty < 23).sum()
total_nonunique_twenty / len(unique_df_twenty)

0.495

40 Students

In [248]:
forty = rng.choice(range(1,366),(1_000,23))
df_forty = pd.DataFrame(forty)
unique_df_forty = df_forty.nunique(axis=1)
total_nonunique_forty = (unique_df_forty < 23).sum()
total_nonunique_forty / len(unique_df_forty)

0.503

Jul 31st Lesson Entry Ticket

In [252]:
dice_roll = rng.choice([1,2,3,4,5,6],(1000,2))
dice_roll

array([[3, 4],
       [1, 3],
       [3, 4],
       ...,
       [6, 5],
       [5, 3],
       [1, 5]])

In [259]:
dice_double = (dice_roll[:,0] % 2 == 0) & (dice_roll[:,1] % 2 == 0)
dice_double

array([False, False, False, False, False, False, False,  True, False,
       False, False,  True, False, False,  True, False, False, False,
       False, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False,  True,
       False,  True, False, False,  True, False, False,  True, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False,  True,  True, False, False, False, False,  True,
       False, False, False,  True, False,  True, False,  True, False,
       False,  True,

In [264]:
dice_double.sum() / len(dice_roll)

0.252

In [262]:
dice_double.mean()

0.252